web_app/web_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from website.views import *
from website.views import profile, logout_user

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
]

urlpatterns += [
    url(r"^$",Login.as_view(), name="account_login"),
    url(r"^accounts/login/$", Login.as_view(), name="account_login"),
    url(r"^accounts/signup/$", Signup.as_view(), name="account_signup"),
    url(r"^confirm-email/(?P<key>[-:\w]+)/$", ConfirmEmail.as_view(), name="account_confirm_email"),
    url(r"^email/$",Email.as_view(), name="account_email"),
    url(r"^dashboard/$", profile, name="profile"),
    url(r"^logout/$", logout_user, name="logout"),
    url(r"^test/$",test_user, name="test"),
    url(r"^check_contact/$", check_user_contact, name="check_contact")
]

web_app/website/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Place(models.Model):
    place_name = models.CharField(max_length=100)

class Restaurant(models.Model):
    restaurant_name = models.CharField(max_length=100)
    place = models.OneToOneField(Place)

web_app/website/forms.py
from allauth.account.forms import LoginForm, SignupForm
from django import forms


class UserLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

        self.fields['login'].widget.attrs['class'] = 'input-field'
        self.fields['password'].widget.attrs['class'] = 'input-field'

class UserSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super(UserSignupForm, self).__init__(*args, **kwargs)

        self.fields['email'].label = "Email"
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['email'].widget.attrs['class'] = 'input-field'

        self.fields['username'].required = False
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['username'].widget.attrs['class'] = 'input-field'

        self.fields['password1'].widget.attrs['class'] = 'input-field'

        del self.fields['password2']


class UserProfile(forms.Form):
    name  = forms.CharField(label="Name", max_length=100)
    contact_no = forms.CharField(required=False)
    name.widget.attrs.update({'class':'input-field'})
    name.widget.attrs.update({'placeholder': 'Name'})
    contact_no.widget.attrs.update({'class':'input-field'})
    contact_no.widget.attrs.update({'placeholder':'Mobile No'})

web_app/website/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from allauth.account.views import SignupView, LoginView, ConfirmEmailView, EmailView, LogoutView
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
import json
from website.forms import *
from django.shortcuts import render, redirect

class Login(LoginView):
    form_class = UserLoginForm
    template_name = "login.html"

class Signup(SignupView):
    template_name = "signup.html"
    form_class = UserSignupForm

class ConfirmEmail(ConfirmEmailView):
    template_name = "email-confirmation.html"

class Email(EmailView):
    template_name = ""

def logout_user(request):
    logout(request)
    return redirect('/')

def profile(request):
    if request.method == 'POST':
        form = UserProfile(request.POST)
        if form.is_valid():
         return HttpResponse("Thanks")
    else:
        form = UserProfile(initial = {'name':request.user.username})

        return render(request, 'profile.html', {"form":form})

def check_user_contact(request):
    if request.method == 'GET':
        contact = request.GET.get('contact_number')
        if contact == "123":
            return HttpResponse(json.dumps("True"), content_type="application/json")
        else:
            return HttpResponse(json.dumps("False"), content_type="application/json")

def test_user(request):
    return HttpResponseRedirect("http://google.com/")

web_app/templates/base.html
<html>
{% load i18n %}
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />
<body>
<div class="logout-position">
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Logout</button>
</div>
<form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <div class="container">
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Modal Header</h4>
                    </div>
                    <div class="modal-body">
                        <p>Some text in the modal.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" value="Submit">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% block content %}
{% endblock %}
</body>
</html>

web_app/templates/email-confirmation.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Confirm E-mail Address" %}{% endblock %}


{% block content %}
<h1>{% trans "Confirm E-mail Address" %}</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
{% csrf_token %}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

{% endif %}

{% endblock %}

web_app/templates/login.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />

<div class="parent">
<div class="center-div">

{% load i18n %}
{% block content %}

<h1 class="center-text">{% trans "Sign In" %}</h1>
<form class="login, center-div" method="POST" action="{% url 'account_login' %}">
  {% csrf_token %}
  {{ form.as_p }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
{#  <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>#}
  <button class="primaryAction, submit-button" type="submit">{% trans "Sign In" %}</button>
</form>
<p class="center-text">{% blocktrans %}If you have not created an account yet, then please
<a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
{% endblock %}

</div>
</div>

web_app/templates/profile.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>


    $(document).ready(function () {
        $("form").submit(function (e) {
            var contact_number = $('#id_contact_no').val()
            $.ajax({
                type: 'GET',
                url: '/check_contact/',
                async:false,
                data: {
                    'contact_number': contact_number
                },
                success: function (result) {
                    if (result == 'True') {
                        alert('success')
                    }
                    else {
                        e.preventDefault()
                    }
                }
            });
        });
    });

</script>

{% extends "base.html" %}
{% block content %}
    <div class="parent">
        <div class="center-div">
            <form method="post" class="center-div" action="{% url 'profile' %}">
                {% csrf_token %}
                {{ form }}
                <button type="submit" onclick="return contactVerify()" value="Submit" class="submit-button">Submit
                </button>
            </form>
        </div>
    </div>
{% endblock %}

web_app/templates/signup.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />

<div class="parent">
<div class="center-div">
    {% load i18n %}

    {% block content %}
        <h1 class="center-text">{% trans "Sign Up" %}</h1>

        <form class="signup, center-div" id="signup_form" method="post" action="{% url 'account_signup' %}">
            {% csrf_token %}
            {{ form.as_p }}
            {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
            {% endif %}
            <button type="submit" class="submit-button">{% trans "Sign Up" %}</button>
        </form>

        <p class="center-text">{% blocktrans %}Already have an account? Then please <a href="{{ login_url }}">sign in</a>
            .{% endblocktrans %}</p>
    {% endblock %}

</div>
</div>